import type {
  Banner,
  BannerPoolEntry,
  FeaturedGroup,
  GachaFeaturedRule,
  GachaItem,
  GachaRarityRule,
} from "./types";

const DEFAULT_RARITY_RULES: GachaRarityRule[] = [
  {
    rarity: 5,
    baseRatePpm: 6000,
    rollOrder: 1,
    hardPity: 80,
    softPityStart: 66,
    softPityIncrementPpm: 60000,
    resetsLowerRarity: true,
  },
  {
    rarity: 4,
    baseRatePpm: 51000,
    rollOrder: 2,
    hardPity: 10,
    softPityStart: null,
    softPityIncrementPpm: 0,
    resetsLowerRarity: false,
  },
  {
    rarity: 3,
    baseRatePpm: 943000,
    rollOrder: 3,
    softPityIncrementPpm: 0,
    resetsLowerRarity: false,
  },
];

const LIMITED_FEATURED_RULES: GachaFeaturedRule[] = [
  {
    rarity: 5,
    featuredGroup: "five_up",
    featuredRatePpm: 500000,
    guaranteeAfterMiss: true,
    missSetsGuarantee: true,
    guaranteeStateKey: "guaranteed_featured_five",
  },
  {
    rarity: 4,
    featuredGroup: "four_up",
    featuredRatePpm: 600000,
    guaranteeAfterMiss: false,
    missSetsGuarantee: false,
    guaranteeStateKey: null,
  },
];

const STANDARD_FEATURED_RULES: GachaFeaturedRule[] = [
  {
    rarity: 4,
    featuredGroup: "four_up",
    featuredRatePpm: 600000,
    guaranteeAfterMiss: false,
    missSetsGuarantee: false,
    guaranteeStateKey: null,
  },
];

export const GACHA_ITEMS: GachaItem[] = [
  {
    id: "char-luoxian",
    name: "洛弦",
    subtitle: "归潮的观测者",
    rarity: 5,
    type: "character",
    element: "导电",
    role: "主 C",
    faction: "白塔档案局",
    accent: "#f6c453",
    quote: "让风暴归档，让星海回答。",
  },
  {
    id: "char-xingjian",
    name: "星见遥",
    subtitle: "夜航列车长",
    rarity: 5,
    type: "character",
    element: "冷凝",
    role: "速切",
    faction: "环城铁道",
    accent: "#79d7ff",
    quote: "下一站，越过今晚。",
  },
  {
    id: "char-jinli",
    name: "烬璃",
    subtitle: "残阳剑术师",
    rarity: 5,
    type: "character",
    element: "热熔",
    role: "爆发",
    faction: "赤庭",
    accent: "#ff765d",
    quote: "余烬里，也会有新的花。",
  },
  {
    id: "char-qinglan",
    name: "青岚",
    subtitle: "云端巡礼人",
    rarity: 4,
    type: "character",
    element: "气动",
    role: "辅助",
    faction: "九枝会",
    accent: "#64dca8",
    quote: "顺风时，答案会自己走近。",
  },
  {
    id: "char-miyue",
    name: "弥月",
    subtitle: "月相修复师",
    rarity: 4,
    type: "character",
    element: "衍射",
    role: "治疗",
    faction: "月台医院",
    accent: "#d8b4fe",
    quote: "别怕，我会把裂缝补好。",
  },
  {
    id: "char-duoyin",
    name: "铎音",
    subtitle: "钟楼调律员",
    rarity: 4,
    type: "character",
    element: "湮灭",
    role: "副 C",
    faction: "旧城钟楼",
    accent: "#b1b7c8",
    quote: "听见了吗？命运在慢半拍。",
  },
  {
    id: "char-musha",
    name: "暮砂",
    subtitle: "边境记录员",
    rarity: 4,
    type: "character",
    element: "热熔",
    role: "防御",
    faction: "砂舟驿",
    accent: "#e2a463",
    quote: "把危险写下来，它就小了一半。",
  },
  {
    id: "weapon-aurora",
    name: "极昼回声",
    subtitle: "五星音感仪",
    rarity: 5,
    type: "weapon",
    element: "共鸣",
    role: "增幅",
    faction: "古物",
    accent: "#f8e38f",
    quote: "黎明被封存在晶体里。",
  },
  {
    id: "weapon-mirror",
    name: "镜海裁决",
    subtitle: "五星迅刃",
    rarity: 5,
    type: "weapon",
    element: "斩击",
    role: "暴击",
    faction: "古物",
    accent: "#8fd8ff",
    quote: "每一道水纹都指向真相。",
  },
  {
    id: "weapon-bell",
    name: "白昼铃",
    subtitle: "四星音感仪",
    rarity: 4,
    type: "weapon",
    element: "共鸣",
    role: "充能",
    faction: "工坊",
    accent: "#f6d58f",
    quote: "铃声轻响，伤口便睡去。",
  },
  {
    id: "weapon-thorn",
    name: "覆雨棘",
    subtitle: "四星长刃",
    rarity: 4,
    type: "weapon",
    element: "斩击",
    role: "攻击",
    faction: "工坊",
    accent: "#6ed6b3",
    quote: "雨落之前，荆棘先醒。",
  },
  {
    id: "weapon-cinder",
    name: "余温",
    subtitle: "三星迅刃",
    rarity: 3,
    type: "weapon",
    element: "斩击",
    role: "训练",
    faction: "制式",
    accent: "#9aa3b2",
    quote: "仍有一点热度。",
  },
  {
    id: "weapon-tide",
    name: "潮汐笔记",
    subtitle: "三星音感仪",
    rarity: 3,
    type: "weapon",
    element: "共鸣",
    role: "训练",
    faction: "制式",
    accent: "#7fb5cf",
    quote: "初学者的第一页。",
  },
  {
    id: "weapon-iron",
    name: "灰铁",
    subtitle: "三星长刃",
    rarity: 3,
    type: "weapon",
    element: "斩击",
    role: "训练",
    faction: "制式",
    accent: "#a4a09a",
    quote: "可靠，朴素，常被遗忘。",
  },
];

export const BANNERS: Banner[] = [
  {
    id: "banner-luoxian",
    name: "归潮观测",
    shortName: "限定角色",
    type: "limited-character",
    description: "洛弦概率提升。五星角色 50% 命中 UP，未命中后下次五星必定为 UP。",
    endsAt: "静态演示池",
    featuredFiveId: "char-luoxian",
    featuredFourIds: ["char-qinglan", "char-miyue", "weapon-bell"],
    itemPool: [
      "char-luoxian",
      "char-xingjian",
      "char-jinli",
      "char-qinglan",
      "char-miyue",
      "char-duoyin",
      "char-musha",
      "weapon-bell",
      "weapon-thorn",
      "weapon-cinder",
      "weapon-tide",
      "weapon-iron",
    ],
    poolEntries: createPoolEntries(
      [
        "char-luoxian",
        "char-xingjian",
        "char-jinli",
        "char-qinglan",
        "char-miyue",
        "char-duoyin",
        "char-musha",
        "weapon-bell",
        "weapon-thorn",
        "weapon-cinder",
        "weapon-tide",
        "weapon-iron",
      ],
      "char-luoxian",
      ["char-qinglan", "char-miyue", "weapon-bell"],
    ),
    rarityRules: DEFAULT_RARITY_RULES,
    featuredRules: LIMITED_FEATURED_RULES,
    theme: {
      primary: "#f6c453",
      secondary: "#18c7a3",
      glow: "rgba(246, 196, 83, 0.28)",
    },
  },
  {
    id: "banner-standard",
    name: "群星回声",
    shortName: "常驻唤取",
    type: "standard",
    description: "常驻角色与武器混合池。五星无 UP 机制，适合测试完整概率。",
    endsAt: "长期开放",
    featuredFourIds: ["char-duoyin", "char-musha", "weapon-thorn"],
    itemPool: [
      "char-xingjian",
      "char-jinli",
      "weapon-aurora",
      "weapon-mirror",
      "char-qinglan",
      "char-miyue",
      "char-duoyin",
      "char-musha",
      "weapon-bell",
      "weapon-thorn",
      "weapon-cinder",
      "weapon-tide",
      "weapon-iron",
    ],
    poolEntries: createPoolEntries(
      [
        "char-xingjian",
        "char-jinli",
        "weapon-aurora",
        "weapon-mirror",
        "char-qinglan",
        "char-miyue",
        "char-duoyin",
        "char-musha",
        "weapon-bell",
        "weapon-thorn",
        "weapon-cinder",
        "weapon-tide",
        "weapon-iron",
      ],
      undefined,
      ["char-duoyin", "char-musha", "weapon-thorn"],
    ),
    rarityRules: DEFAULT_RARITY_RULES,
    featuredRules: STANDARD_FEATURED_RULES,
    theme: {
      primary: "#79d7ff",
      secondary: "#ff8f70",
      glow: "rgba(121, 215, 255, 0.22)",
    },
  },
];

export const ITEM_BY_ID = Object.fromEntries(
  GACHA_ITEMS.map((item) => [item.id, item]),
) as Record<string, GachaItem>;

function createPoolEntries(
  itemPool: string[],
  featuredFiveId: string | undefined,
  featuredFourIds: string[],
): BannerPoolEntry[] {
  return itemPool.map((itemId, index) => {
    let featuredGroup: FeaturedGroup | null = null;
    if (itemId === featuredFiveId) {
      featuredGroup = "five_up";
    } else if (featuredFourIds.includes(itemId)) {
      featuredGroup = "four_up";
    }

    return {
      itemId,
      poolGroup: featuredGroup ? "featured" : "standard",
      featuredGroup,
      weight: 1,
      sortOrder: index,
    };
  });
}
