export type ElementCategory =
  | "alkali-metal"
  | "alkaline-earth"
  | "transition-metal"
  | "post-transition-metal"
  | "metalloid"
  | "reactive-nonmetal"
  | "halogen"
  | "noble-gas"
  | "lanthanide"
  | "actinide"
  | "unknown";

export interface PeriodicElement {
  number: number;
  symbol: string;
  name: string;
  group: number;
  row: number;
  mass: string;
  category: ElementCategory;
}

export const categoryLabels: Record<ElementCategory, string> = {
  "alkali-metal": "碱金属",
  "alkaline-earth": "碱土金属",
  "transition-metal": "过渡金属",
  "post-transition-metal": "后过渡金属",
  metalloid: "类金属",
  "reactive-nonmetal": "反应性非金属",
  halogen: "卤素",
  "noble-gas": "稀有气体",
  lanthanide: "镧系",
  actinide: "锕系",
  unknown: "待定性质",
};

export const categoryOrder: ElementCategory[] = [
  "alkali-metal",
  "alkaline-earth",
  "transition-metal",
  "post-transition-metal",
  "metalloid",
  "reactive-nonmetal",
  "halogen",
  "noble-gas",
  "lanthanide",
  "actinide",
  "unknown",
];

export const categoryColors: Record<
  ElementCategory,
  { fill: string; stroke: string; text: string; accent: string }
> = {
  "alkali-metal": {
    fill: "#ffe7a8",
    stroke: "#d99820",
    text: "#5b3b00",
    accent: "#f6b333",
  },
  "alkaline-earth": {
    fill: "#dff2b1",
    stroke: "#83a92c",
    text: "#314400",
    accent: "#9fc23a",
  },
  "transition-metal": {
    fill: "#d9ecff",
    stroke: "#4d91ce",
    text: "#0d3557",
    accent: "#4a9fe8",
  },
  "post-transition-metal": {
    fill: "#d9f4ee",
    stroke: "#4ca391",
    text: "#073d33",
    accent: "#41b39f",
  },
  metalloid: {
    fill: "#f2e0c7",
    stroke: "#aa7c45",
    text: "#4a2d10",
    accent: "#c48c48",
  },
  "reactive-nonmetal": {
    fill: "#e4ddff",
    stroke: "#8972d9",
    text: "#2d235c",
    accent: "#8d77e8",
  },
  halogen: {
    fill: "#ffdce8",
    stroke: "#d06b91",
    text: "#5d1832",
    accent: "#e36a97",
  },
  "noble-gas": {
    fill: "#d8f3ff",
    stroke: "#4d9ab8",
    text: "#083747",
    accent: "#3eb8d8",
  },
  lanthanide: {
    fill: "#f7d5c8",
    stroke: "#c56c48",
    text: "#55200d",
    accent: "#d97855",
  },
  actinide: {
    fill: "#f2d4f3",
    stroke: "#b264b5",
    text: "#4d1c50",
    accent: "#bd69c1",
  },
  unknown: {
    fill: "#e5e7eb",
    stroke: "#9ca3af",
    text: "#27272a",
    accent: "#71717a",
  },
};

export const periodicRows: Record<number, string> = {
  1: "1",
  2: "2",
  3: "3",
  4: "4",
  5: "5",
  6: "6",
  7: "7",
  8: "镧系",
  9: "锕系",
};

export const periodicElements: PeriodicElement[] = [
  {
    number: 1,
    symbol: "H",
    name: "氢",
    group: 1,
    row: 1,
    mass: "1.008",
    category: "reactive-nonmetal",
  },
  { number: 2, symbol: "He", name: "氦", group: 18, row: 1, mass: "4.0026", category: "noble-gas" },
  { number: 3, symbol: "Li", name: "锂", group: 1, row: 2, mass: "6.94", category: "alkali-metal" },
  {
    number: 4,
    symbol: "Be",
    name: "铍",
    group: 2,
    row: 2,
    mass: "9.0122",
    category: "alkaline-earth",
  },
  { number: 5, symbol: "B", name: "硼", group: 13, row: 2, mass: "10.81", category: "metalloid" },
  {
    number: 6,
    symbol: "C",
    name: "碳",
    group: 14,
    row: 2,
    mass: "12.011",
    category: "reactive-nonmetal",
  },
  {
    number: 7,
    symbol: "N",
    name: "氮",
    group: 15,
    row: 2,
    mass: "14.007",
    category: "reactive-nonmetal",
  },
  {
    number: 8,
    symbol: "O",
    name: "氧",
    group: 16,
    row: 2,
    mass: "15.999",
    category: "reactive-nonmetal",
  },
  { number: 9, symbol: "F", name: "氟", group: 17, row: 2, mass: "18.998", category: "halogen" },
  {
    number: 10,
    symbol: "Ne",
    name: "氖",
    group: 18,
    row: 2,
    mass: "20.180",
    category: "noble-gas",
  },
  {
    number: 11,
    symbol: "Na",
    name: "钠",
    group: 1,
    row: 3,
    mass: "22.990",
    category: "alkali-metal",
  },
  {
    number: 12,
    symbol: "Mg",
    name: "镁",
    group: 2,
    row: 3,
    mass: "24.305",
    category: "alkaline-earth",
  },
  {
    number: 13,
    symbol: "Al",
    name: "铝",
    group: 13,
    row: 3,
    mass: "26.982",
    category: "post-transition-metal",
  },
  {
    number: 14,
    symbol: "Si",
    name: "硅",
    group: 14,
    row: 3,
    mass: "28.085",
    category: "metalloid",
  },
  {
    number: 15,
    symbol: "P",
    name: "磷",
    group: 15,
    row: 3,
    mass: "30.974",
    category: "reactive-nonmetal",
  },
  {
    number: 16,
    symbol: "S",
    name: "硫",
    group: 16,
    row: 3,
    mass: "32.06",
    category: "reactive-nonmetal",
  },
  { number: 17, symbol: "Cl", name: "氯", group: 17, row: 3, mass: "35.45", category: "halogen" },
  {
    number: 18,
    symbol: "Ar",
    name: "氩",
    group: 18,
    row: 3,
    mass: "39.948",
    category: "noble-gas",
  },
  {
    number: 19,
    symbol: "K",
    name: "钾",
    group: 1,
    row: 4,
    mass: "39.098",
    category: "alkali-metal",
  },
  {
    number: 20,
    symbol: "Ca",
    name: "钙",
    group: 2,
    row: 4,
    mass: "40.078",
    category: "alkaline-earth",
  },
  {
    number: 21,
    symbol: "Sc",
    name: "钪",
    group: 3,
    row: 4,
    mass: "44.956",
    category: "transition-metal",
  },
  {
    number: 22,
    symbol: "Ti",
    name: "钛",
    group: 4,
    row: 4,
    mass: "47.867",
    category: "transition-metal",
  },
  {
    number: 23,
    symbol: "V",
    name: "钒",
    group: 5,
    row: 4,
    mass: "50.942",
    category: "transition-metal",
  },
  {
    number: 24,
    symbol: "Cr",
    name: "铬",
    group: 6,
    row: 4,
    mass: "51.996",
    category: "transition-metal",
  },
  {
    number: 25,
    symbol: "Mn",
    name: "锰",
    group: 7,
    row: 4,
    mass: "54.938",
    category: "transition-metal",
  },
  {
    number: 26,
    symbol: "Fe",
    name: "铁",
    group: 8,
    row: 4,
    mass: "55.845",
    category: "transition-metal",
  },
  {
    number: 27,
    symbol: "Co",
    name: "钴",
    group: 9,
    row: 4,
    mass: "58.933",
    category: "transition-metal",
  },
  {
    number: 28,
    symbol: "Ni",
    name: "镍",
    group: 10,
    row: 4,
    mass: "58.693",
    category: "transition-metal",
  },
  {
    number: 29,
    symbol: "Cu",
    name: "铜",
    group: 11,
    row: 4,
    mass: "63.546",
    category: "transition-metal",
  },
  {
    number: 30,
    symbol: "Zn",
    name: "锌",
    group: 12,
    row: 4,
    mass: "65.38",
    category: "transition-metal",
  },
  {
    number: 31,
    symbol: "Ga",
    name: "镓",
    group: 13,
    row: 4,
    mass: "69.723",
    category: "post-transition-metal",
  },
  {
    number: 32,
    symbol: "Ge",
    name: "锗",
    group: 14,
    row: 4,
    mass: "72.630",
    category: "metalloid",
  },
  {
    number: 33,
    symbol: "As",
    name: "砷",
    group: 15,
    row: 4,
    mass: "74.922",
    category: "metalloid",
  },
  {
    number: 34,
    symbol: "Se",
    name: "硒",
    group: 16,
    row: 4,
    mass: "78.971",
    category: "reactive-nonmetal",
  },
  { number: 35, symbol: "Br", name: "溴", group: 17, row: 4, mass: "79.904", category: "halogen" },
  {
    number: 36,
    symbol: "Kr",
    name: "氪",
    group: 18,
    row: 4,
    mass: "83.798",
    category: "noble-gas",
  },
  {
    number: 37,
    symbol: "Rb",
    name: "铷",
    group: 1,
    row: 5,
    mass: "85.468",
    category: "alkali-metal",
  },
  {
    number: 38,
    symbol: "Sr",
    name: "锶",
    group: 2,
    row: 5,
    mass: "87.62",
    category: "alkaline-earth",
  },
  {
    number: 39,
    symbol: "Y",
    name: "钇",
    group: 3,
    row: 5,
    mass: "88.906",
    category: "transition-metal",
  },
  {
    number: 40,
    symbol: "Zr",
    name: "锆",
    group: 4,
    row: 5,
    mass: "91.224",
    category: "transition-metal",
  },
  {
    number: 41,
    symbol: "Nb",
    name: "铌",
    group: 5,
    row: 5,
    mass: "92.906",
    category: "transition-metal",
  },
  {
    number: 42,
    symbol: "Mo",
    name: "钼",
    group: 6,
    row: 5,
    mass: "95.95",
    category: "transition-metal",
  },
  {
    number: 43,
    symbol: "Tc",
    name: "锝",
    group: 7,
    row: 5,
    mass: "98",
    category: "transition-metal",
  },
  {
    number: 44,
    symbol: "Ru",
    name: "钌",
    group: 8,
    row: 5,
    mass: "101.07",
    category: "transition-metal",
  },
  {
    number: 45,
    symbol: "Rh",
    name: "铑",
    group: 9,
    row: 5,
    mass: "102.91",
    category: "transition-metal",
  },
  {
    number: 46,
    symbol: "Pd",
    name: "钯",
    group: 10,
    row: 5,
    mass: "106.42",
    category: "transition-metal",
  },
  {
    number: 47,
    symbol: "Ag",
    name: "银",
    group: 11,
    row: 5,
    mass: "107.87",
    category: "transition-metal",
  },
  {
    number: 48,
    symbol: "Cd",
    name: "镉",
    group: 12,
    row: 5,
    mass: "112.41",
    category: "transition-metal",
  },
  {
    number: 49,
    symbol: "In",
    name: "铟",
    group: 13,
    row: 5,
    mass: "114.82",
    category: "post-transition-metal",
  },
  {
    number: 50,
    symbol: "Sn",
    name: "锡",
    group: 14,
    row: 5,
    mass: "118.71",
    category: "post-transition-metal",
  },
  {
    number: 51,
    symbol: "Sb",
    name: "锑",
    group: 15,
    row: 5,
    mass: "121.76",
    category: "metalloid",
  },
  {
    number: 52,
    symbol: "Te",
    name: "碲",
    group: 16,
    row: 5,
    mass: "127.60",
    category: "metalloid",
  },
  { number: 53, symbol: "I", name: "碘", group: 17, row: 5, mass: "126.90", category: "halogen" },
  {
    number: 54,
    symbol: "Xe",
    name: "氙",
    group: 18,
    row: 5,
    mass: "131.29",
    category: "noble-gas",
  },
  {
    number: 55,
    symbol: "Cs",
    name: "铯",
    group: 1,
    row: 6,
    mass: "132.91",
    category: "alkali-metal",
  },
  {
    number: 56,
    symbol: "Ba",
    name: "钡",
    group: 2,
    row: 6,
    mass: "137.33",
    category: "alkaline-earth",
  },
  {
    number: 72,
    symbol: "Hf",
    name: "铪",
    group: 4,
    row: 6,
    mass: "178.49",
    category: "transition-metal",
  },
  {
    number: 73,
    symbol: "Ta",
    name: "钽",
    group: 5,
    row: 6,
    mass: "180.95",
    category: "transition-metal",
  },
  {
    number: 74,
    symbol: "W",
    name: "钨",
    group: 6,
    row: 6,
    mass: "183.84",
    category: "transition-metal",
  },
  {
    number: 75,
    symbol: "Re",
    name: "铼",
    group: 7,
    row: 6,
    mass: "186.21",
    category: "transition-metal",
  },
  {
    number: 76,
    symbol: "Os",
    name: "锇",
    group: 8,
    row: 6,
    mass: "190.23",
    category: "transition-metal",
  },
  {
    number: 77,
    symbol: "Ir",
    name: "铱",
    group: 9,
    row: 6,
    mass: "192.22",
    category: "transition-metal",
  },
  {
    number: 78,
    symbol: "Pt",
    name: "铂",
    group: 10,
    row: 6,
    mass: "195.08",
    category: "transition-metal",
  },
  {
    number: 79,
    symbol: "Au",
    name: "金",
    group: 11,
    row: 6,
    mass: "196.97",
    category: "transition-metal",
  },
  {
    number: 80,
    symbol: "Hg",
    name: "汞",
    group: 12,
    row: 6,
    mass: "200.59",
    category: "transition-metal",
  },
  {
    number: 81,
    symbol: "Tl",
    name: "铊",
    group: 13,
    row: 6,
    mass: "204.38",
    category: "post-transition-metal",
  },
  {
    number: 82,
    symbol: "Pb",
    name: "铅",
    group: 14,
    row: 6,
    mass: "207.2",
    category: "post-transition-metal",
  },
  {
    number: 83,
    symbol: "Bi",
    name: "铋",
    group: 15,
    row: 6,
    mass: "208.98",
    category: "post-transition-metal",
  },
  {
    number: 84,
    symbol: "Po",
    name: "钋",
    group: 16,
    row: 6,
    mass: "209",
    category: "post-transition-metal",
  },
  { number: 85, symbol: "At", name: "砹", group: 17, row: 6, mass: "210", category: "halogen" },
  { number: 86, symbol: "Rn", name: "氡", group: 18, row: 6, mass: "222", category: "noble-gas" },
  { number: 87, symbol: "Fr", name: "钫", group: 1, row: 7, mass: "223", category: "alkali-metal" },
  {
    number: 88,
    symbol: "Ra",
    name: "镭",
    group: 2,
    row: 7,
    mass: "226",
    category: "alkaline-earth",
  },
  {
    number: 104,
    symbol: "Rf",
    name: "𬬻",
    group: 4,
    row: 7,
    mass: "267",
    category: "transition-metal",
  },
  {
    number: 105,
    symbol: "Db",
    name: "𬭊",
    group: 5,
    row: 7,
    mass: "268",
    category: "transition-metal",
  },
  {
    number: 106,
    symbol: "Sg",
    name: "𬭳",
    group: 6,
    row: 7,
    mass: "269",
    category: "transition-metal",
  },
  {
    number: 107,
    symbol: "Bh",
    name: "𬭛",
    group: 7,
    row: 7,
    mass: "270",
    category: "transition-metal",
  },
  {
    number: 108,
    symbol: "Hs",
    name: "𬭶",
    group: 8,
    row: 7,
    mass: "277",
    category: "transition-metal",
  },
  { number: 109, symbol: "Mt", name: "鿏", group: 9, row: 7, mass: "278", category: "unknown" },
  { number: 110, symbol: "Ds", name: "𫟼", group: 10, row: 7, mass: "281", category: "unknown" },
  { number: 111, symbol: "Rg", name: "𬬭", group: 11, row: 7, mass: "282", category: "unknown" },
  {
    number: 112,
    symbol: "Cn",
    name: "鎶",
    group: 12,
    row: 7,
    mass: "285",
    category: "transition-metal",
  },
  { number: 113, symbol: "Nh", name: "鉨", group: 13, row: 7, mass: "286", category: "unknown" },
  {
    number: 114,
    symbol: "Fl",
    name: "𫓧",
    group: 14,
    row: 7,
    mass: "289",
    category: "post-transition-metal",
  },
  { number: 115, symbol: "Mc", name: "镆", group: 15, row: 7, mass: "290", category: "unknown" },
  {
    number: 116,
    symbol: "Lv",
    name: "𫟷",
    group: 16,
    row: 7,
    mass: "293",
    category: "post-transition-metal",
  },
  { number: 117, symbol: "Ts", name: "鿬", group: 17, row: 7, mass: "294", category: "unknown" },
  { number: 118, symbol: "Og", name: "奥气", group: 18, row: 7, mass: "294", category: "unknown" },
  {
    number: 57,
    symbol: "La",
    name: "镧",
    group: 4,
    row: 8,
    mass: "138.91",
    category: "lanthanide",
  },
  {
    number: 58,
    symbol: "Ce",
    name: "铈",
    group: 5,
    row: 8,
    mass: "140.12",
    category: "lanthanide",
  },
  {
    number: 59,
    symbol: "Pr",
    name: "镨",
    group: 6,
    row: 8,
    mass: "140.91",
    category: "lanthanide",
  },
  {
    number: 60,
    symbol: "Nd",
    name: "钕",
    group: 7,
    row: 8,
    mass: "144.24",
    category: "lanthanide",
  },
  { number: 61, symbol: "Pm", name: "钷", group: 8, row: 8, mass: "145", category: "lanthanide" },
  {
    number: 62,
    symbol: "Sm",
    name: "钐",
    group: 9,
    row: 8,
    mass: "150.36",
    category: "lanthanide",
  },
  {
    number: 63,
    symbol: "Eu",
    name: "铕",
    group: 10,
    row: 8,
    mass: "151.96",
    category: "lanthanide",
  },
  {
    number: 64,
    symbol: "Gd",
    name: "钆",
    group: 11,
    row: 8,
    mass: "157.25",
    category: "lanthanide",
  },
  {
    number: 65,
    symbol: "Tb",
    name: "铽",
    group: 12,
    row: 8,
    mass: "158.93",
    category: "lanthanide",
  },
  {
    number: 66,
    symbol: "Dy",
    name: "镝",
    group: 13,
    row: 8,
    mass: "162.50",
    category: "lanthanide",
  },
  {
    number: 67,
    symbol: "Ho",
    name: "钬",
    group: 14,
    row: 8,
    mass: "164.93",
    category: "lanthanide",
  },
  {
    number: 68,
    symbol: "Er",
    name: "铒",
    group: 15,
    row: 8,
    mass: "167.26",
    category: "lanthanide",
  },
  {
    number: 69,
    symbol: "Tm",
    name: "铥",
    group: 16,
    row: 8,
    mass: "168.93",
    category: "lanthanide",
  },
  {
    number: 70,
    symbol: "Yb",
    name: "镱",
    group: 17,
    row: 8,
    mass: "173.05",
    category: "lanthanide",
  },
  {
    number: 71,
    symbol: "Lu",
    name: "镥",
    group: 18,
    row: 8,
    mass: "174.97",
    category: "lanthanide",
  },
  { number: 89, symbol: "Ac", name: "锕", group: 4, row: 9, mass: "227", category: "actinide" },
  { number: 90, symbol: "Th", name: "钍", group: 5, row: 9, mass: "232.04", category: "actinide" },
  { number: 91, symbol: "Pa", name: "镤", group: 6, row: 9, mass: "231.04", category: "actinide" },
  { number: 92, symbol: "U", name: "铀", group: 7, row: 9, mass: "238.03", category: "actinide" },
  { number: 93, symbol: "Np", name: "镎", group: 8, row: 9, mass: "237", category: "actinide" },
  { number: 94, symbol: "Pu", name: "钚", group: 9, row: 9, mass: "244", category: "actinide" },
  { number: 95, symbol: "Am", name: "镅", group: 10, row: 9, mass: "243", category: "actinide" },
  { number: 96, symbol: "Cm", name: "锔", group: 11, row: 9, mass: "247", category: "actinide" },
  { number: 97, symbol: "Bk", name: "锫", group: 12, row: 9, mass: "247", category: "actinide" },
  { number: 98, symbol: "Cf", name: "锎", group: 13, row: 9, mass: "251", category: "actinide" },
  { number: 99, symbol: "Es", name: "锿", group: 14, row: 9, mass: "252", category: "actinide" },
  { number: 100, symbol: "Fm", name: "镄", group: 15, row: 9, mass: "257", category: "actinide" },
  { number: 101, symbol: "Md", name: "钔", group: 16, row: 9, mass: "258", category: "actinide" },
  { number: 102, symbol: "No", name: "锘", group: 17, row: 9, mass: "259", category: "actinide" },
  { number: 103, symbol: "Lr", name: "铹", group: 18, row: 9, mass: "266", category: "actinide" },
];

export const categoryCounts = categoryOrder.map((category) => ({
  category,
  label: categoryLabels[category],
  count: periodicElements.filter((element) => element.category === category).length,
}));
